# Generated by Django 5.2.3 on 2025-06-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Students_model',
        ),
    ]
