# Generated by Django 5.2.3 on 2025-06-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teachers_model',
        ),
    ]
